const studioData = [
  {id:1,
    "img":"/imges/s1.jpg",
    "name":"CONCERT RATRI 2.0",
    "address":["Phoneix Marketcity","chennai","Concerts"]},
  {id:2,
    "img":"/imges/s2.jpg",
    "name":"OFR LIVE NINAITHALE INIKKUM",
    "address":["Phoneix Marketcity","chennai","Concerts"]},
  {id:3,
    "img":"/imges/s3.jpg",
    "name":"CONCERT VIJAY PRAKASH",
    "address":["Phoneix Marketcity","chennai","Concerts"]},
  {id:4,
    "img":"/imges/s4.jpg",
    "name":"K S CHITRA",
    "address":["Phoneix Marketcity","chennai","Concerts"]},
  {id:5,
    "img":"/imges/s5.jpg",
    "name":"MIRCHU RETRO",
    "address":["Phoneix Marketcity","chennai","Concerts"]},
      {id:6,
    "img":"/imges/s1.jpg",
    "name":"CONCERT RATRI 2.0",
    "address":["Phoneix Marketcity","chennai","Concerts"]},
  {id:7,
    "img":"/imges/s2.jpg",
    "name":"OFR LIVE NINAITHALE INIKKUM",
    "address":["Phoneix Marketcity","chennai","Concerts"]},
  {id:8,
    "img":"/imges/s3.jpg",
    "name":"CONCERT VIJAY PRAKASH",
    "address":["Phoneix Marketcity","chennai","Concerts"]},
  {id:9,
    "img":"/imges/s4.jpg",
    "name":"K S CHITRA",
    "address":["Phoneix Marketcity","chennai","Concerts"]},
  {id:10,
    "img":"/imges/s5.jpg",
    "name":"MIRCHU RETRO",
    "address":["Phoneix Marketcity","chennai","Concerts"]},
      {id:11,
    "img":"/imges/s5.jpg",
    "name":"MIRCHU RETRO",
    "address":["Phoneix Marketcity","chennai","Concerts"]},
];

const outDoorData =[
    {id:1,
    "img":"/imges/po1.jpg",
    "name":" SOUNDS OF INDIA",
    "address":["Phoneix Marketcity","chennai","Concerts"],
    },
        {id:2,
    "img":"/imges/po2.jpg",
    "name":"VIR DAS SOUNDS OF INDIA",
    "address":["Phoneix Marketcity","chennai","Concerts"],
    },
        {id:3,
    "img":"/imges/po3.jpg",
    "name":"VIR DAS  OF INDIA",
    "address":["Phoneix Marketcity","chennai","Concerts"],
    },
        {id:4,
    "img":"/imges/po4.jpg",
    "name":"VIR DAS OF INDIA",
    "address":["Phoneix Marketcity","chennai","Concerts"],
    },
        {id:5,
    "img":"/imges/po5.jpg",
    "name":"VIR  INDIA",
    "address":["Phoneix Marketcity","chennai","Concerts"],
    },
    {id:1,
    "img":"/imges/po1.jpg",
    "name":" SOUNDS OF INDIA",
    "address":["Phoneix Marketcity","chennai","Concerts"],
    },
        {id:2,
    "img":"/imges/po2.jpg",
    "name":"VIR DAS SOUNDS OF INDIA",
    "address":["Phoneix Marketcity","chennai","Concerts"],
    },
        {id:3,
    "img":"/imges/po3.jpg",
    "name":"VIR DAS  OF INDIA",
    "address":["Phoneix Marketcity","chennai","Concerts"],
    },
        {id:4,
    "img":"/imges/po4.jpg",
    "name":"VIR DAS OF INDIA",
    "address":["Phoneix Marketcity","chennai","Concerts"],
    },
        {id:5,
    "img":"/imges/po5.jpg",
    "name":"VIR  INDIA",
    "address":["Phoneix Marketcity","chennai","Concerts"],
    },
            {id:5,
    "img":"/imges/po5.jpg",
    "name":"VIR  INDIA",
    "address":["Phoneix Marketcity","chennai","Concerts"],
    },
];

const therepyData =[
    {id:1,
      "img":"/imges/po6.jpg",
 "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:2,
      "img":"/imges/po2.jpg",
           "name":"VIR  INDIA",
 "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:3,
      "img":"/imges/po1.jpg",
       "name":"VIR  INDIA",
 "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:4,
      "img":"/imges/po7.jpg",
           "name":"VIR  INDIA",
 "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:5,
      "img":"/imges/po8.jpg",
            "name":"VIR  INDIA",
 "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:1,
      "img":"/imges/po6.jpg",
           "name":"VIR  INDIA",
 "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:2,
      "img":"/imges/po2.jpg",
           "name":"VIR  INDIA",
 "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:3,
      "img":"/imges/po1.jpg",
             "name":"VIR  INDIA",
 "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:4,
      "img":"/imges/po7.jpg",
       "name":"VIR  INDIA",
 "address":["Phoneix Marketcity","chennai","Concerts"]},
     {id:5,
      "img":"/imges/po8.jpg",
          "name":"VIR  INDIA",
    "address":["Phoneix Marketcity","chennai","Concerts"]}
];


const popularData =[
    {id:1,
      "img":"/imges/po2.jpg",
      "name":"VIR DAS SOUNDS OF INDIA",
       "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:2,
      "img":"/imges/po9.jpg",
      "name":"VIR DAS SOUNDS OF INDIA",
      "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:3,
      "img":"/imges/po10.jpg",
      "name":"VIR DAS SOUNDS OF INDIA",
      "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:4,
      "img":"/imges/po3.jpg",
      "name":"VIR DAS SOUNDS OF INDIA",
      "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:5,
      "img":"/imges/po11.jpg",
      "name":"VIR DAS SOUNDS OF INDIA",
      "address":["Phoneix Marketcity","chennai","Concerts"]},
          {id:1,
      "img":"/imges/po2.jpg",
      "name":"VIR DAS SOUNDS OF INDIA",
      "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:2,
      "img":"/imges/po9.jpg",
      "name":"VIR DAS SOUNDS OF INDIA",
      "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:3,
      "img":"/imges/po10.jpg",
      "name":"VIR DAS SOUNDS OF INDIA",
     "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:4,
      "img":"/imges/po3.jpg",
      "name":"VIR DAS SOUNDS OF INDIA",
     "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:5,
      "img":"/imges/po11.jpg",
      "name":"VIR DAS SOUNDS OF INDIA",
       "address":["Phoneix Marketcity","chennai","Concerts"]},
]

const LastPlayData =[
    {id:1,
      "name":"VIR DAS SOUNDS OF INDIA",
      "img":"/imges/po12.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:2,
      "name":"VIR DAS SOUNDS OF INDIA",
      "img":"/imges/po13.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:3,
      "name":"VIR DAS SOUNDS OF INDIA",
      "img":"/imges/po4.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:4,
      "name":"VIR DAS SOUNDS OF INDIA",
      "img":"/imges/po7.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:5,
      "name":"VIR DAS SOUNDS OF INDIA",
      "img":"/imges/po5.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
          {id:1,
      "name":"VIR DAS SOUNDS OF INDIA",
      "img":"/imges/po12.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:2,
      "name":"VIR DAS SOUNDS OF INDIA",
      "img":"/imges/po13.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:3,
      "name":"VIR DAS SOUNDS OF INDIA",
      "img":"/imges/po4.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:4,
      "name":"VIR DAS SOUNDS OF INDIA",
      "img":"/imges/po7.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:5,
      "name":"VIR DAS SOUNDS OF INDIA",
      "img":"/imges/po5.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]}
    ]

const topGameData =[
    {id:1,
      "name":"VIR DAS SOUNDS ",
      "img":"/imges/po5.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:2,
      "name":"VIR DAS SOUNDS OF INDIA",
      "img":"/imges/po14.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:3,
      "name":"VIR DAS SOUNDS",
      "img":"/imges/po15.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:4,
      "name":"VIR DAS SOUNDS OF INDIA",
      "img":"/imges/po8.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:5,
      "name":"VIR DAS SOUNDS ",
      "img":"/imges/po16.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
          {id:1,
      "name":"VIR DAS SOUNDS ",
      "img":"/imges/po5.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:2,
      "name":"VIR DAS SOUNDS OF INDIA",
      "img":"/imges/po14.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:3,
      "name":"VIR DAS SOUNDS",
      "img":"/imges/po15.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:4,
      "name":"VIR DAS SOUNDS OF INDIA",
      "img":"/imges/po8.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
    {id:5,
      "name":"VIR DAS SOUNDS ",
      "img":"/imges/po16.jpg", "address":["Phoneix Marketcity","chennai","Concerts"]},
]

export {topGameData,LastPlayData,popularData,therepyData,outDoorData,studioData} ;

