const district = [
  { "id": 1, "state": "Tamil Nadu", "district": "Chennai" },
  { "id": 2, "state": "Tamil Nadu", "district": "Coimbatore" },
  { "id": 3, "state": "Tamil Nadu", "district": "Madurai" },
  { "id": 4, "state": "Tamil Nadu", "district": "Tiruchirappalli" },
  { "id": 5, "state": "Tamil Nadu", "district": "Salem" },
  { "id": 6, "state": "Tamil Nadu", "district": "Erode" },
  { "id": 7, "state": "Tamil Nadu", "district": "Vellore" },
  { "id": 8, "state": "Tamil Nadu", "district": "Tirunelveli" },
  { "id": 9, "state": "Tamil Nadu", "district": "Thoothukudi" },
  { "id": 10, "state": "Tamil Nadu", "district": "Thanjavur" },
  { "id": 11, "state": "Tamil Nadu", "district": "Kanchipuram" },
  { "id": 12, "state": "Tamil Nadu", "district": "Nagapattinam" },
  { "id": 13, "state": "Tamil Nadu", "district": "Dindigul" },
  { "id": 14, "state": "Tamil Nadu", "district": "Cuddalore" },
  { "id": 15, "state": "Tamil Nadu", "district": "Dharmapuri" },
  { "id": 16, "state": "Tamil Nadu", "district": "Krishnagiri" },
  { "id": 17, "state": "Tamil Nadu", "district": "Sivaganga" },
  { "id": 18, "state": "Tamil Nadu", "district": "Namakkal" },
  { "id": 19, "state": "Tamil Nadu", "district": "Pudukottai" },
  { "id": 20, "state": "Tamil Nadu", "district": "Virudhunagar" },

  { "id": 21, "state": "Kerala", "district": "Thiruvananthapuram" },
  { "id": 22, "state": "Kerala", "district": "Kollam" },
  { "id": 23, "state": "Kerala", "district": "Pathanamthitta" },
  { "id": 24, "state": "Kerala", "district": "Alappuzha" },
  { "id": 25, "state": "Kerala", "district": "Kottayam" },
  { "id": 26, "state": "Kerala", "district": "Idukki" },
  { "id": 27, "state": "Kerala", "district": "Ernakulam" },
  { "id": 28, "state": "Kerala", "district": "Thrissur" },
  { "id": 29, "state": "Kerala", "district": "Palakkad" },
  { "id": 30, "state": "Kerala", "district": "Malappuram" },

  { "id": 31, "state": "Andhra Pradesh", "district": "Visakhapatnam" },
  { "id": 32, "state": "Andhra Pradesh", "district": "Vijayawada" },
  { "id": 33, "state": "Andhra Pradesh", "district": "Guntur" },
  { "id": 34, "state": "Andhra Pradesh", "district": "Nellore" },
  { "id": 35, "state": "Andhra Pradesh", "district": "Kurnool" },
  { "id": 36, "state": "Andhra Pradesh", "district": "Chittoor" },
  { "id": 37, "state": "Andhra Pradesh", "district": "Anantapur" },
  { "id": 38, "state": "Andhra Pradesh", "district": "Kadapa" },
  { "id": 39, "state": "Andhra Pradesh", "district": "Prakasam" },
  { "id": 40, "state": "Andhra Pradesh", "district": "West Godavari" },

  { "id": 41, "state": "Maharashtra", "district": "Mumbai City" },
  { "id": 42, "state": "Maharashtra", "district": "Mumbai Suburban" },
  { "id": 43, "state": "Maharashtra", "district": "Thane" },
  { "id": 44, "state": "Maharashtra", "district": "Pune" },
  { "id": 45, "state": "Maharashtra", "district": "Nagpur" },

  { "id": 46, "state": "Delhi", "district": "New Delhi" },
  { "id": 47, "state": "Delhi", "district": "North Delhi" },
  { "id": 48, "state": "Delhi", "district": "South Delhi" },
  { "id": 49, "state": "Delhi", "district": "East Delhi" },
  { "id": 50, "state": "Delhi", "district": "West Delhi" },

  { "id": 51, "state": "West Bengal", "district": "Kolkata" },
  { "id": 52, "state": "West Bengal", "district": "Howrah" },
  { "id": 53, "state": "West Bengal", "district": "Hooghly" },
  { "id": 54, "state": "West Bengal", "district": "North 24 Parganas" },
  { "id": 55, "state": "West Bengal", "district": "South 24 Parganas" },

  { "id": 56, "state": "Karnataka", "district": "Bengaluru Urban" },
  { "id": 57, "state": "Karnataka", "district": "Bengaluru Rural" },
  { "id": 58, "state": "Karnataka", "district": "Mysuru" },
  { "id": 59, "state": "Karnataka", "district": "Mangaluru" },
  { "id": 60, "state": "Karnataka", "district": "Belagavi" },
  { "id": 61, "state": "Karnataka", "district": "Hubballi" },
  { "id": 62, "state": "Karnataka", "district": "Ballari" },
  { "id": 63, "state": "Karnataka", "district": "Shivamogga" },
  { "id": 64, "state": "Karnataka", "district": "Davangere" },
  { "id": 65, "state": "Karnataka", "district": "Tumakuru" },

  { "id": 66, "state": "Rajasthan", "district": "Jaipur" },
  { "id": 67, "state": "Rajasthan", "district": "Jodhpur" },
  { "id": 68, "state": "Rajasthan", "district": "Udaipur" },
  { "id": 69, "state": "Rajasthan", "district": "Kota" },
  { "id": 70, "state": "Rajasthan", "district": "Ajmer" },

  { "id": 71, "state": "Punjab", "district": "Amritsar" },
  { "id": 72, "state": "Punjab", "district": "Ludhiana" },
  { "id": 73, "state": "Punjab", "district": "Jalandhar" },
  { "id": 74, "state": "Punjab", "district": "Patiala" },
  { "id": 75, "state": "Punjab", "district": "Bathinda" },

  { "id": 76, "state": "Haryana", "district": "Gurugram" },
  { "id": 77, "state": "Haryana", "district": "Faridabad" },
  { "id": 78, "state": "Haryana", "district": "Panipat" },
  { "id": 79, "state": "Haryana", "district": "Ambala" },
  { "id": 80, "state": "Haryana", "district": "Hisar" },

  { "id": 81, "state": "Madhya Pradesh", "district": "Bhopal" },
  { "id": 82, "state": "Madhya Pradesh", "district": "Indore" },
  { "id": 83, "state": "Madhya Pradesh", "district": "Gwalior" },
  { "id": 84, "state": "Madhya Pradesh", "district": "Jabalpur" },
  { "id": 85, "state": "Madhya Pradesh", "district": "Ujjain" },

  { "id": 86, "state": "Gujarat", "district": "Ahmedabad" },
  { "id": 87, "state": "Gujarat", "district": "Surat" },
  { "id": 88, "state": "Gujarat", "district": "Vadodara" },
  { "id": 89, "state": "Gujarat", "district": "Rajkot" },
  { "id": 90, "state": "Gujarat", "district": "Bhavnagar" },

  { "id": 91, "state": "Bihar", "district": "Patna" },
  { "id": 92, "state": "Bihar", "district": "Gaya" },
  { "id": 93, "state": "Bihar", "district": "Muzaffarpur" },
  { "id": 94, "state": "Bihar", "district": "Bhagalpur" },
  { "id": 95, "state": "Bihar", "district": "Darbhanga" },

  { "id": 96, "state": "Odisha", "district": "Bhubaneswar" },
  { "id": 97, "state": "Odisha", "district": "Cuttack" },
  { "id": 98, "state": "Odisha", "district": "Puri" },
  { "id": 99, "state": "Odisha", "district": "Rourkela" },
  { "id": 100, "state": "Odisha", "district": "Sambalpur" }
]

export default district;
