const movieDetails =  [
  {
    "id": 1,
    "movie_name": "Idli Kadai",
     "img":"/imges/img1.jpg",
    "languages": ["Tamil"],
    "cast": ["Sivakarthikeyan", "Priya Bhavani Shankar"],
    "crew": {
      "director": "Raja Murugan",
      "producer": "Dream House Studios",
      "music_director": "Anirudh Ravichander"
    },
    "about_movie": "A fun-filled comedy-drama set around a small idli shop and the lives it touches.",
    "time_duration": "2h 18m",
    "release_date": "2024-06-14",
    "release_year": 2024,
    "visuals": ["2D"],
    "movie_format": ["Comedy", "Drama"],
    "censor_code": "U",
    "rating": 7.6,
    "likes": 45200,
    "votes": 12000
  },
  {
    "id": 2,
    "movie_name": "They Call Him OG",
     "img":"/imges/img2.jpg",
    "languages": ["Telugu", "Tamil", "Hindi"],
    "cast": ["Pawan Kalyan", "Emraan Hashmi", "Priyanka Arul Mohan"],
    "crew": {
      "director": "Sujeeth",
      "producer": "DVV Danayya",
      "music_director": "Thaman S"
    },
    "about_movie": "An action-packed gangster story exploring the rise of a feared don.",
    "time_duration": "2h 45m",
    "release_date": "2024-09-27",
    "release_year": 2024,
    "visuals": ["2D", "IMAX"],
    "movie_format": ["Action", "Crime", "Thriller"],
    "censor_code": "A",
    "rating": 8.2,
    "likes": 256000,
    "votes": 89000
  },
  {
    "id": 3,
    "movie_name": "Lokah",
    "languages": ["Malayalam", "Tamil"],
     "img":"/imges/img3.jpg",
    "cast": ["Tovino Thomas", "Keerthy Suresh"],
    "crew": {
      "director": "Basil Joseph",
      "producer": "Good Cinema Works",
      "music_director": "Bijibal"
    },
    "about_movie": "A mystical fantasy where a young hero discovers his destiny across two worlds.",
    "time_duration": "2h 32m",
    "release_date": "2025-01-12",
    "release_year": 2025,
    "visuals": ["3D"],
    "movie_format": ["Fantasy", "Adventure", "Drama"],
    "censor_code": "UA",
    "rating": 7.9,
    "likes": 75000,
    "votes": 30210
  },
  {
    "id": 4,
    "movie_name": "Shakthi Thirmagan",
    "languages": ["Tamil"],
     "img":"/imges/img4.jpg",
    "cast": ["Vishal", "Trisha Krishnan"],
    "crew": {
      "director": "Hari",
      "producer": "Studio Green",
      "music_director": "Yuvan Shankar Raja"
    },
    "about_movie": "A police officer fights against corruption and injustice in a gripping drama.",
    "time_duration": "2h 20m",
    "release_date": "2023-11-10",
    "release_year": 2023,
    "visuals": ["2D"],
    "movie_format": ["Action", "Drama"],
    "censor_code": "UA",
    "rating": 7.1,
    "likes": 34000,
    "votes": 9800
  },
  {
    "id": 5,
    "movie_name": "Balti",
    "languages": ["Hindi"],
     "img":"/imges/img5.jpg",
    "cast": ["Rajkummar Rao", "Shraddha Kapoor"],
    "crew": {
      "director": "Anubhav Sinha",
      "producer": "Benaras Media",
      "music_director": "Amit Trivedi"
    },
    "about_movie": "A slice-of-life comedy about a man whose life changes after a quirky encounter.",
    "time_duration": "2h 05m",
    "release_date": "2024-04-22",
    "release_year": 2024,
    "visuals": ["2D"],
    "movie_format": ["Comedy", "Romance"],
    "censor_code": "U",
    "rating": 6.9,
    "likes": 15000,
    "votes": 4200
  },
  {
    "id": 6,
    "movie_name": "Shin Chan: They Spicy Kasukabe Dancers in India",
     "img":"/imges/img6.jpg",
    "languages": ["Japanese", "Hindi", "Tamil"],
    "cast": ["Shinnosuke Nohara", "Kazama", "Bo-chan"],
    "crew": {
      "director": "Keiichi Hara",
      "producer": "Shin-Ei Animation",
      "music_director": "Shiro Sagisu"
    },
    "about_movie": "Shin Chan and friends travel to India where chaos follows in a hilarious dance adventure.",
    "time_duration": "1h 40m",
    "release_date": "2025-05-05",
    "release_year": 2025,
    "visuals": ["2D"],
    "movie_format": ["Animation", "Comedy", "Family"],
    "censor_code": "U",
    "rating": 8.4,
    "likes": 110000,
    "votes": 50200
  },
  {
    "id": 7,
    "movie_name": "Kantra: A Legend Chapter-1",
     "img":"/imges/img7.jpg",
    "languages": ["Kannada", "Hindi", "Tamil", "Telugu"],
    "cast": ["Rishab Shetty", "Sapthami Gowda"],
    "crew": {
      "director": "Rishab Shetty",
      "producer": "Hombale Films",
      "music_director": "Ajaneesh Loknath"
    },
    "about_movie": "A mythological action thriller set in coastal Karnataka, exploring folklore and legends.",
    "time_duration": "2h 38m",
    "release_date": "2025-08-15",
    "release_year": 2025,
    "visuals": ["2D", "IMAX"],
    "movie_format": ["Action", "Mythology", "Thriller"],
    "censor_code": "UA",
    "rating": 8.5,
    "likes": 187000,
    "votes": 64000
  },
  {
    "id": 8,
    "movie_name": "Madharasi",
     "img":"/imges/img10.jpg",
    "languages": ["Tamil"],
    "cast": ["Arjun Sarja", "Sonali Bendre"],
    "crew": {
      "director": "P. Vasu",
      "producer": "Lakshmi Movie Makers",
      "music_director": "D. Imman"
    },
    "about_movie": "An action-packed entertainer where a cop uncovers a powerful criminal nexus.",
    "time_duration": "2h 30m",
    "release_date": "2006-06-29",
    "release_year": 2006,
    "visuals": ["2D"],
    "movie_format": ["Action", "Thriller"],
    "censor_code": "UA",
    "rating": 6.3,
    "likes": 21000,
    "votes": 6200
  },
  {
    "id": 9,
    "movie_name": "Mirai",
     "img":"/imges/img8.jpg",
    "languages": ["Japanese", "English", "Hindi"],
    "cast": ["Moka Kamishiraishi", "Haru Kuroki"],
    "crew": {
      "director": "Mamoru Hosoda",
      "producer": "Studio Chizu",
      "music_director": "Masakatsu Takagi"
    },
    "about_movie": "A boy discovers a magical garden that allows him to meet his relatives from different eras.",
    "time_duration": "1h 38m",
    "release_date": "2018-07-20",
    "release_year": 2018,
    "visuals": ["2D"],
    "movie_format": ["Animation", "Fantasy", "Family"],
    "censor_code": "U",
    "rating": 7.0,
    "likes": 88000,
    "votes": 26000
  },
  {
    "id": 10,
    "movie_name": "Kiss Me Idiot",
     "img":"/imges/img19.jpg",
    "languages": ["English"],
    "cast": ["Diane Kruger", "Jean Reno"],
    "crew": {
      "director": "Pierre Morel",
      "producer": "EuropaCorp",
      "music_director": "Alexandre Desplat"
    },
    "about_movie": "A romantic comedy-drama filled with witty dialogues and emotional twists.",
    "time_duration": "1h 55m",
    "release_date": "2025-02-14",
    "release_year": 2025,
    "visuals": ["2D"],
    "movie_format": ["Romance", "Comedy", "Drama"],
    "censor_code": "UA",
    "rating": 6.8,
    "likes": 14500,
    "votes": 5000
  },
  {
    "id": 11,
    "movie_name": "The Conjuring: Last Rites",
     "img":"/imges/img9.jpg",
    "languages": ["English"],
    "cast": ["Patrick Wilson", "Vera Farmiga"],
    "crew": {
      "director": "Michael Chaves",
      "producer": "Warner Bros.",
      "music_director": "Joseph Bishara"
    },
    "about_movie": "The Warrens face their darkest supernatural case in the chilling finale.",
    "time_duration": "2h 12m",
    "release_date": "2025-09-05",
    "release_year": 2025,
    "visuals": ["2D", "IMAX"],
    "movie_format": ["Horror", "Thriller", "Mystery"],
    "censor_code": "A",
    "rating": 7.8,
    "likes": 203000,
    "votes": 82000
  },
  {
    "id": 12,
    "movie_name": "Kushi",
     "img":"/imges/img13.jpg",
    "languages": ["Tamil", "Telugu"],
    "cast": ["Vijay", "Jyothika"],
    "crew": {
      "director": "S. J. Surya",
      "producer": "A. M. Rathnam",
      "music_director": "Deva"
    },
    "about_movie": "Two college students fall in love, but their egos and misunderstandings test their relationship.",
    "time_duration": "2h 52m",
    "release_date": "2000-05-19",
    "release_year": 2000,
    "visuals": ["2D"],
    "movie_format": ["Romance", "Drama"],
    "censor_code": "U",
    "rating": 7.5,
    "likes": 156000,
    "votes": 49000
  },
  {
    "id": 13,
    "movie_name": "One Battle After Another",
     "img":"/imges/img12.jpg",
    "languages": ["English"],
    "cast": ["Chris Hemsworth", "Charlize Theron"],
    "crew": {
      "director": "Ridley Scott",
      "producer": "Paramount Pictures",
      "music_director": "Hans Zimmer"
    },
    "about_movie": "A war epic chronicling a general’s survival through endless battles.",
    "time_duration": "2h 50m",
    "release_date": "2024-12-20",
    "release_year": 2024,
    "visuals": ["IMAX", "3D"],
    "movie_format": ["War", "Action", "Drama"],
    "censor_code": "UA",
    "rating": 8.1,
    "likes": 98000,
    "votes": 35000
  },
  {
    "id": 14,
    "movie_name": "F1: The Movie",
     "img":"/imges/img11.jpg",
    "languages": ["English"],
    "cast": ["Lewis Hamilton", "Charles Leclerc"],
    "crew": {
      "director": "Joseph Kosinski",
      "producer": "Apple Studios",
      "music_director": "Harold Faltermeyer"
    },
    "about_movie": "A high-octane racing drama following the lives of Formula 1 champions.",
    "time_duration": "2h 15m",
    "release_date": "2025-06-27",
    "release_year": 2025,
    "visuals": ["IMAX"],
    "movie_format": ["Sports", "Drama"],
    "censor_code": "UA",
    "rating": 8.0,
    "likes": 167000,
    "votes": 62000
  },
  {
    "id": 15,
    "movie_name": "BTS 2016 HYYH On Stage: Epilogue Remastered",
     "img":"/imges/img18.jpg",
    "languages": ["Korean", "English"],
    "cast": ["RM", "Jin", "Suga", "J-Hope", "Jimin", "V", "Jungkook"],
    "crew": {
      "director": "BigHit Entertainment",
      "producer": "HYBE",
      "music_director": "BTS"
    },
    "about_movie": "A remastered concert film showcasing BTS’s powerful performances during the HYYH era.",
    "time_duration": "2h 30m",
    "release_date": "2025-07-07",
    "release_year": 2025,
    "visuals": ["2D"],
    "movie_format": ["Concert", "Documentary", "Music"],
    "censor_code": "U",
    "rating": 9.2,
    "likes": 325000,
    "votes": 210000
  },
  {
    "id": 16,
    "movie_name": "Jolly LLB 3",
     "img":"/imges/img16.jpg",
    "languages": ["Hindi"],
    "cast": ["Akshay Kumar", "Arshad Warsi"],
    "crew": {
      "director": "Subhash Kapoor",
      "producer": "Fox Star Studios",
      "music_director": "Sachin–Jigar"
    },
    "about_movie": "A courtroom comedy-drama where two lawyers face off in a high-profile case.",
    "time_duration": "2h 35m",
    "release_date": "2025-03-21",
    "release_year": 2025,
    "visuals": ["2D"],
    "movie_format": ["Comedy", "Drama", "Courtroom"],
    "censor_code": "UA",
    "rating": 7.7,
    "likes": 88000,
    "votes": 29000
  },
  {
    "id": 17,
    "movie_name": "Vinnaithandi Varuvaaya",
    "languages": ["Tamil"],
     "img":"/imges/img15.jpg",
    "cast": ["Simbu", "Trisha Krishnan"],
    "crew": {
      "director": "Gautham Vasudev Menon",
      "producer": "Escape Artists Motion Pictures",
      "music_director": "A. R. Rahman"
    },
    "about_movie": "A love story between an aspiring filmmaker and a woman from a conservative family.",
    "time_duration": "2h 37m",
    "release_date": "2010-02-26",
    "release_year": 2010,
    "visuals": ["2D"],
    "movie_format": ["Romance", "Drama"],
    "censor_code": "UA",
    "rating": 8.0,
    "likes": 140000,
    "votes": 52000
  },
  {
    "id": 18,
    "movie_name": "Ajex: The Untold Story of Yogi",
     "img":"/imges/img17.jpg",
    "languages": ["Hindi", "Tamil"],
    "cast": ["Ranveer Singh", "Keerthy Suresh"],
    "crew": {
      "director": "Prashanth Neel",
      "producer": "Hombale Films",
      "music_director": "Ravi Basrur"
    },
    "about_movie": "A high-voltage action thriller about Yogi’s mysterious journey and rise as Ajex.",
    "time_duration": "2h 42m",
    "release_date": "2025-12-25",
    "release_year": 2025,
    "visuals": ["IMAX", "3D"],
    "movie_format": ["Action", "Thriller", "Drama"],
    "censor_code": "A",
    "rating": 8.6,
    "likes": 215000,
    "votes": 75000
  }
]

export default movieDetails;
